export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const BACKEND = 'BACKEND';
export const GET_BLOG_ITEMS = "GET_BLOG_ITEMS";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_ITEM_SUCCESS = "GET_BLOG_ITEM_SUCCESS";